<template>
  <div class="p-4">
    <!-- skeleton when loading -->
    <div v-if="isLoading">
      <div class="animate-pulse mb-2">
        <div class="h-10 w-full rounded-md grainy dark:bg-blend-overlay"></div>
      </div>
      <div class="flex flex-wrap gap-2 mt-4">
        <div
          v-for="i in 6"
          :key="i"
          class="py-1 px-2 rounded-md flex gap-2 items-center justify-between animate-pulse grainy dark:bg-blend-overlay"
        >
          <div class="size-6"></div>
          <div class="w-16 h-4"></div>
        </div>
      </div>
    </div>

    <!-- actual content -->
    <div v-else>
      <div class="flex items-center gap-2 mb-4">
        <input
          v-model="searchQuery"
          type="text"
          class="flex-grow rounded-md p-2 dark:bg-blend-overlay grainy font-medium text-lg focus:outline-none"
          placeholder="Search tags..."
        />

        <button
          @click="createNewTag"
          class="text-primary rounded-md border-primary border-1 p-2 flex items-center gap-1 hover:opacity-90"
        >
          <PlusCircleIcon class="size-6" />
          New Tag
        </button>
      </div>

      <!-- Tags display section -->
      <div class="flex flex-wrap gap-2 mt-4">
        <TaskTag
          v-for="tag in filteredTags"
          :key="tag.id"
          :name="tag.name"
          :hex_color="tag.hex_color"
          class="w-fit"
          @click="selectTag(tag)"
        ></TaskTag>
      </div>
      <div
        v-if="filteredTags.length === 0"
        class="col-span-full text-center p-4 text-text/70"
      >
        No tags found matching your search.
      </div>
    </div>

    <!-- Tag detail panel -->
    <Transition :name="isDesktop ? 'list-slide-right' : 'page-slide'">
      <AppPageTag
        v-if="selectedTag"
        :tag="selectedTag"
        :key="selectedTag.id || 'new-tag'"
        :is-new="!selectedTag.id"
        :anchor="isDesktop ? 'right' : 'left'"
        :widthClass="isDesktop ? 'w-128' : ''"
        :class="[isDesktop ? 'border-l border-text/10' : '']"
        @close="selectedTag = null"
        @tag-updated="onTagUpdated"
        @tag-created="onTagCreated"
      />
    </Transition>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref, computed } from "vue";
import { useTagsStore } from "../stores/tags";
import { type Tag } from "../common/types";
import AppPageTag from "./AppPageTag.vue";
import { useBreakpoints } from "../common/breakpoints";
import TaskTag from "./TaskTag.vue";
import { PlusCircleIcon } from "@heroicons/vue/24/solid";
import { generateRandomColor } from "../common/colorUtils";

onMounted(async () => {
  try {
    await tagsStore.loadTags();
  } finally {
    isLoading.value = false;
  }
});

const tagsStore = useTagsStore();
const isLoading = ref(true);
const searchQuery = ref("");
const selectedTag = ref<Tag | null>(null);
const { isDesktop } = useBreakpoints();

const filteredTags = computed(() => {
  if (!searchQuery.value) {
    return tagsStore.tags;
  }
  const query = searchQuery.value.toLowerCase();
  return tagsStore.tags.filter((tag: Tag) =>
    tag.name.toLowerCase().includes(query)
  );
});

const selectTag = (tag: Tag) => {
  selectedTag.value = tag;
};

const createNewTag = () => {
  selectedTag.value = {
    id: "", // Will be generated by the database
    name: "",
    hex_color: generateRandomColor(),
    user_id: "",
    created_at: "",
  } as Tag;
};

const onTagUpdated = (_updatedTag: Tag) => {
  // Close the detail panel
  selectedTag.value = null;
};

const onTagCreated = (_newTag: Tag) => {
  // Close the detail panel
  selectedTag.value = null;
};
</script>
